export const productData = [
    
    {
        id: "999",
        src: "/images/img-9.png",
        src2: "/images/7acres.jpg",
        name: "Craft Collective: Pink Kush",
        brand: "7ACERS",
        sih: "Hybrid",
        percent: "THC: 22% | CBD: 1%",
        thc: 22,
        cbd: 2,
        description: "7ACRES Craft Collective selected this particular Pink Kush for its intensely pungent fuel notes, high-THC levels, and rock-hard density. This is a terpene-rich, indica-dominant hybrid that has an aroma of heavy diesel notes and hints of flowery perfume and citrus. This descendant of OG Kush is small batch, indoor craft-grown in BC. The full plant is hang-dried, hand-trimmed, and masterfully cured. Limited quantities available.",
        about: "7ACRES believes that everyone should be able to buy high quality cannabis products for reasonable prices. They remain one of the very few private, 100% Canadian owned and operated companies in the cannabis industry, and they maintain a family-oriented mindset towards staff and all of their patients and customers across the country. • 100% Canadian homegrown • 100% Greenhouse grown • Natural growing conditions",

        price: 47.99,
        btns: "1",
        type: "Flower",
        new: "yes",
    },
    {
        id: "1",
        src: "/images/img-1.png",
        name: "Sensi Star2",
        brand: "7ACERS",
        sih: "Indica",
        percent: "THC: 21% | CBD: 1%",
        thc: 21,
        cbd: 1,
        path: "/product/1",
        price: 38.40,
        btns: "1",
        type: "Edibles",
    },
    {
        id: "2",
        id2: "7",
        src: "/images/img-2.png",
        name: "White Widow",
        brand: "7ACERS",
        sih: "Hybrid",
        percent: "THC: 14% | CBD: 5%",
        thc: 14,
        cbd: 5,
        path: "/product/2",
        price: 34.04,
        price7: 59.25,
        btns: "2",
        type: "Vaporizers",
    },
    {
        id: "3",
        src: "/images/img-3.png",
        name: "Cabaret",
        brand: "ALTAVIE",
        sih: "Sativa",
        percent: "THC: 14% | CBD: 2%",
        thc: 14,
        cbd: 2,
        path: "/product/3",
        price: 29.47,
        btns: "1",
        type: "Flower",
    },
    {
        id: "4",
        id2: "8",
        src: "/images/img-4.png",
        name: "Blue Dream",
        brand: "AURORA",
        sih: "Sativa",
        percent: "THC: 13% | CBD: 1%",
        thc: 13,
        cbd: 1,
        path: "/product/4",
        price: 33.04,
        price7: 62.95,
        btns: "2",
        type: "Flower",
        new: "yes",
    },
    {
        id: "5",
        src: "/images/img-5.png",
        name: "Banana Split",
        brand: "AURORA",
        sih: "Hybrid",
        percent: "THC: 18% | CBD: 1%",
        thc: 18,
        cbd: 1,
        path: "/product/5",
        price: 33.04,
        btns: "1",
        type: "Pre-Rolls",
    },
    {
        id: "12",
        src: "/images/img-5.png",
        name: "Gagan kush",
        brand: "LOOOOL",
        sih: "Hybrid",
        percent: "THC: 18% | CBD: 1%",
        thc: 18,
        cbd: 1,
        path: "/product/5",
        price: 33.04,
        price7: 100.01,
        btns: "2",
        type: "Pre-Rolls",
    },
];